### ISSUE TITLE
Upgrade to the latest tensorflow ?

### ISSUE THREAD

**Issue by StevenLOL** [guillaume-chevalier/LSTM-Human-Activity-Recognition#1]
The tensorflow used here is out-of-date, the latest tensorflow has something change in the rnn and rnn_cell. So it will be great if one can upgrade this project.

**Comment by guillaume-chevalier** [comment]
I updated it from version r0.8 to version r0.10 with this commit right here: https://github.com/guillaume-chevalier/LSTM-Human-Activity-Recognition/tree/3bacfe9b5a7e7d2b4dab3fa2f339408eeff3402b

Yet I did not test it with the newest official TensorFlow release r0.11 since I have other projects in parallel. 
If someone can confirm that it works in that version too it will be appreciated.

**Comment by GDissard** [comment]
I ran your code on the r0.11 and it worked :+1:

**Comment by GDissard** [comment]
however it doesnt work on the 0.12 version (on windows10). None of my LSTM scripts work.

Anybody knows what changed  with this version ?
